### ISSUE TITLE
求助，使用后正文中代码块部分配色错误

### ISSUE THREAD

**Issue by Max66888** [AurLemon/wikijs-citizen-styles#1]
求助，使用后正文中代码块部分配色错误
![image](https://github.com/user-attachments/assets/a4a16a34-d114-4dd0-805b-b1c347a096f8)
代码块部分背景颜色也变成白色了，选中文本颜色和背景颜色一致导致选中文本看不见，代码块部分配色异常

**Comment by AurLemon** [comment]
草，有网址吗，我康康

**Comment by Max66888** [comment]
感谢大佬抽空回复！
http://nas.maxcs.icu:5794/
现在是使用了CSS的

> 草，有网址吗，我康康
> 
> （不过选中文本的颜色都是灰色的，然后和代码块的可能一个色容易看不清）

**Comment by AurLemon** [comment]
> 感谢大佬抽空回复！ http://nas.maxcs.icu:5794/zh/Python%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E7%AC%94%E8%AE%B0/MySQL/%E8%AF%AD%E6%B3%95%E7%AC%94%E8%AE%B0 现在是使用了CSS的
> 
> > 草，有网址吗，我康康
> > （不过选中文本的颜色都是灰色的，然后和代码块的可能一个色容易看不清）

太礼貌了（））（）（）（）（）第一次被人提issue

刚刚发了个 [Release](https://github.com/AurLemon/wikijs-citizen-styles/releases/tag/1.0.2)，应该解决了 √

把代码块里面的选中颜色和黄色看不清的问题解决了（才发现 Wikijs 给 `code` 和 `pre` 标签单独写了个 `::selection` 样式）

**Comment by Max66888** [comment]
> > 感谢大佬抽空回复！ http://nas.maxcs.icu:5794/zh/Python%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E7%AC%94%E8%AE%B0/MySQL/%E8%AF%AD%E6%B3%95%E7%AC%94%E8%AE%B0 现在是使用了CSS的
> > > 草，有网址吗，我康康
> > > （不过选中文本的颜色都是灰色的，然后和代码块的可能一个色容易看不清）
> 
> 太礼貌了（））（）（）（）（）第一次被人提 Issue
> 
> ![](https://camo.githubusercontent.com/480ff4eb5d5021d926c1f5e86c581144f8212ae8bec5986d9286be675fad1d94/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f31312f32312f7635456d334e4454754b59727a37502e706e67) 刚刚发了个 [Release](https://github.com/AurLemon/wikijs-citizen-styles/releases/tag/1.0.2)，应该好了 √
> 
> 把代码块里面的选中颜色和黄色看不清的问题解决了（才发现 Wikijs 给 `code` 和 `pre` 标签单独写了个 `::selection` 样式）

太感谢大佬了！半夜还在回复QAQ，我没学过CSS，请问有没有办法自定义这个每个部分的颜色，比如有没有注释啥的，想给选中颜色都改为粉色，以及代码块内代码高亮的颜色，现在的这个好丑，要是有注释的话我就可以自己填颜色啦

**Comment by AurLemon** [comment]
> > > 感谢大佬抽空回复！ http://nas.maxcs.icu:5794/zh/Python%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E7%AC%94%E8%AE%B0/MySQL/%E8%AF%AD%E6%B3%95%E7%AC%94%E8%AE%B0 现在是使用了CSS的
> > > > 草，有网址吗，我康康
> > > > （不过选中文本的颜色都是灰色的，然后和代码块的可能一个色容易看不清）
> > 
> > 
> > 太礼貌了（））（）（）（）（）第一次被人提 Issue
> > ![](https://camo.githubusercontent.com/480ff4eb5d5021d926c1f5e86c581144f8212ae8bec5986d9286be675fad1d94/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f31312f32312f7635456d334e4454754b59727a37502e706e67) 刚刚发了个 [Release](https://github.com/AurLemon/wikijs-citizen-styles/releases/tag/1.0.2)，应该好了 √
> > 把代码块里面的选中颜色和黄色看不清的问题解决了（才发现 Wikijs 给 `code` 和 `pre` 标签单独写了个 `::selection` 样式）
> 
> 太感谢大佬了！半夜还在回复QAQ，我没学过CSS，请问有没有办法自定义这个每个部分的颜色，比如有没有注释啥的，想给选中颜色都改为粉色，以及代码块内代码高亮的颜色，现在的这个好丑，要是有注释的话我就可以自己填颜色啦

注释 OK 的但是可能要晚几天（） 太久了我自己也有点忘记了

但是没关系，如果可以的话不妨尝试着自己改改，选中颜色的选择器是 `::selection`，代码块选中颜色的选择器是 `code[class*=language-]::selection, code[class*=language-] ::selection, pre[class*=language-]::selection, pre[class*=language-] ::selection`。找到他们然后改掉就行。

```css
/* 全局选择文本的样式 */
::selection {
    background: hsla(var(--color-primary-override__h), 5%, 54%, 22%);
}

/* 代码块选择文本的样式 */
code[class*=language-]::selection, code[class*=language-] ::selection, pre[class*=language-]::selection, pre[class*=language-] ::selection {
    background: hsla(var(--color-primary-override__h), 5%, 54%, 22%);
}
```

直接修改丢进去的 CSS 就行（但是压缩过的可能看着有点难受，草），打开 HTML 底部注入那个页面，按 Ctrl+F 直接搜索选择器，然后把后面的 `background` 对应的值改了就行（CSS 的 background 属性支持 RGB、RGBA、十六进制、HSL 反正很多）。如果是代码高亮的话，修改你想要的颜色，然后丢 Wikijs 里面就好（加在原来 CSS 的后面）。
```css
/* 代码块高亮标签的颜色 */
.token.cdata, .token.comment, .token.doctype, .token.prolog /* 设置注释和文档声明的颜色 */ {
    color: #787878;
}

.token.boolean, .token.deleted, .token.number, .token.tag /* 设置布尔值、数值、标签名和删除内容的样式 */ {
    color: #cf694a;
}

.token.builtin, .token.constant, .token.keyword, .token.property, .token.selector, .token.symbol /* 设置与语法核心相关的关键字、内置符号等的样式 */ {
    color: #f9ee9a;
}

.language-css .token.string, .style .token.string, .token.attr-name, .token.attr-value, .token.char, .token.entity, .token.inserted, .token.operator, .token.string, .token.url, .token.variable /* 设置字符串、属性、URL 和变量等的样式 */ {
    color: #919e6b;
}

.token.atrule /* 为 CSS 中的 @ 开头的规则定义样式 */ {
    color: #7386a5;
}

.token.important, .token.regex /* 为正则表达式和重要标记定义样式 */ {
    color: #e9c163;
}

.language-markup .token.attr-name, .language-markup .token.punctuation, .language-markup .token.tag /* 为 HTML/XML 的属性名、标点符号和标签定义样式 */ {
    color: #ad895c;
}
```

上面的这些都是 Wikijs 的默认样式，刚刚我改的黄色就是第三个 `.token.builtin, .token.constant, .token.keyword, .token.property, .token.selector, .token.symbol` 这个选择器的颜色，有需要的话可以先自己改，我过几天改的时候顺带看看能不能更方便的修改（）

其实 Release 的 styles.css 是压行过的，直接把 src/styles.css 里面的 CSS 包裹在 `<style type="text/css"></style>` 内也是可以的
